version: '3'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword

  openmrs-reference-application:
    depends_on:
      - mysql
    image: giorgioazzinnaro/openmrs-reference-application:2.6.0
    ports:
      - "80:8080"
    restart: always

volumes:
  mysql_data:
